# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- firstpatch

pool:
  vmImage: 'ubuntu-latest'

variables:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption v-ololim (7c538e7a-33f0-4611-b6c2-980b246d264b)'
    appType: 'webAppLinux'
    appName: 'devops700'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'

